[build]
  publish = "/"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301


# Role-based admin protection
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/admin/*"
  to = "/unauthorized.html"
  status = 200
